import inspect




length_rules = ['add_free_point','add_circle','add_free_circle',"circle_with_radius", 'add_free_point_with_line', 'add_line', 
                # 'C_add_free_point', 'C_add_circle', 'C_add_free_circle', 'C_circle_with_radius', 'C_add_free_point_with_line', 'C_add_line',
                    #   'C_length_1', 'C_length_2', 'C_length_3', 'C_length_4', 'C_length_5', 'C_length_6', 'C_length_7', 'C_length_8', 'C_length_9',
                      'length_1','length_2','length_3','length_4','length_5','length_6','length_7','length_8', 'length_9']



color_angle_rules = [
    # 'add_free_point','add_circle','add_free_circle',"circle_with_radius",'C_add_free_point', 'C_add_circle', 'C_add_free_circle', 'C_circle_with_radius', 'add_free_point_with_line', 'C_add_free_point_with_line', 'add_line', 'C_add_line',
    #                 'C_angle1', 'C_angle2', 'C_angle3', 'C_angle4', 'C_angle5', 'C_angle6', 'C_angle7', 'C_angle8', 'C_angle9', 'C_angle10', 'C_angle11', 'C_angle12', 'C_angle13', 'C_angle14', 'C_angle15', 'C_angle16', 'C_angle17',
    #                 'angle1', 'angle2', 'angle3', 'angle4', 'angle5', 'angle6', 'angle7', 'angle8', 'angle9', 'angle10', 'angle11', 'angle12', 'angle13', 'angle14', 'angle15', 'angle16', 'angle17'
                "angle22"
                    ]

angle_only_rules = [
    # 'C_angle1', 'C_angle2', 'C_angle3', 'C_angle4', 'C_angle5', 'C_angle6', 'C_angle7', 'C_angle8', 'C_angle9', 'C_angle10', 'C_angle11', 'C_angle12', 'C_angle13', 'C_angle14', 'C_angle15', 'C_angle16', 'C_angle17',
    #                 'angle1', 'angle2', 'angle3', 'angle4', 'angle5', 'angle6', 'angle7', 'angle8', 'angle9', 'angle10', 'angle11', 'angle12', 'angle13', 'angle14', 'angle15', 'angle16', 'angle17'
"angle22"
]

color_parallel_rules = ['add_free_point','add_circle','add_free_circle',"circle_with_radius",'C_add_free_point', 'C_add_circle', 'C_add_free_circle', 'C_circle_with_radius', 'add_free_point_with_line', 'C_add_free_point_with_line', 'add_line', 'C_add_line',
                        'C_parallel_1', 'C_parallel_2', 'C_parallel_3', 'C_parallel_4',
                        'parallel_1','parallel_2','parallel_3','parallel_4']

color_length_rules = ['add_free_point','add_circle','add_free_circle',"circle_with_radius",'C_add_free_point', 'C_add_circle', 'C_add_free_circle', 'C_circle_with_radius', 'add_free_point_with_line', 'C_add_free_point_with_line', 'add_line', 'C_add_line',
                      'C_length_1', 'C_length_2', 'C_length_3', 'C_length_4', 'C_length_5', 'C_length_6', 'C_length_7', 'C_length_8', 'C_length_9', 'C_length_12', 'C_length_13', 'C_length_14_1', 'C_length_14_2', 'C_length_15', 'C_length_16',
                      'length_1','length_2','length_3','length_4','length_5','length_6','length_7','length_8', 'length_9', 'length_10', 'length_11', 'length_12', 'length_13', 'length_14_1', 'length_14_2', 'length_15', 'length_16', 'length_17_1', 'length_17_2', 'length_17_3']

no_entity_rules = [
'add_free_point', 'add_circle','add_free_circle','add_free_point_with_line', 'add_line', "circle_with_radius",
'add_circle','add_free_circle','add_free_point_with_line', 'add_line', "circle_with_radius",
]

a2_rules = [
    'add_free_point','add_circle','add_free_circle','add_free_point_with_line', 'add_line', "circle_with_radius",
    'add_circle','add_free_circle','add_free_point_with_line', 'add_line', "circle_with_radius",
    'add_circle','add_free_circle','add_free_point_with_line', 'add_line', "circle_with_radius",
    'add_circle','add_free_circle','add_free_point_with_line', 'add_line', "circle_with_radius",
    'add_circle','add_free_circle','add_free_point_with_line', 'add_line', "circle_with_radius",
    'add_free_point','add_circle','add_free_circle','add_free_point_with_line', 'add_line', "circle_with_radius",
    'add_free_point','add_circle','add_free_circle','add_free_point_with_line', 'add_line', "circle_with_radius",
    # 'C_add_free_point', 'C_add_circle', 'C_add_free_circle', 'C_circle_with_radius', 'C_add_free_point_with_line', 'C_add_line',
    'circle_center',
    'angle_bisector',
    'eq_quadrilateral',
    'eq_trapezoid',
    'eqtriangle',
    'eqdia_quadrilateral',
    'eqdistance',
    'foot',
    'incenter',
    'incenter2',
    'tangent',
    "mirror",
    "right_iso",
    "parallelogram",
    "pentagon",
    "quadrilateral",
    "square",
    "triangle",
    "triangle12",
    "on_bline",
    "on_circle",
    "on_pline",
    "trapezoid",
    "on_line",
    'r_triangle',
    'rectangle',
    'reflect',
    'init_square',
    "trisect",
    "trisegment",
    "cc_tangent",
    "eqangle2",
    # "on_aline",
    "rotate90",
    "on_tline",
    "midpointcircle",
    "excenter",
    "orthocenter",
    "r_trapezoid",
    "risos",
    "rotate_angle",
    "shift",
    "on_dia",
    "eqangle3",
    "two_lines_one_circle",
    "centroid",

    ### Original Rules ###
    "on_circle2",
    "inter_ll",
    "one_line_one_circle",
    "colinear",
    "cc_tangent_one",
    "intersect_cl",
    "intersect_cc",
    "touches_cc",
    "touches_cc2",
    "touches_clc",
    "touches_clc2",
    "rhombus",
    "convex_quad",
    "ellipse_line_intersect",
    # "parabola",
    "incenter3",
    "circular_sector",
    "semicircle",
    "l_in_c",
    "l_out_c",
    "ll_angle",
    "ccl1",
    "ccl2",
    "ccl3",
    "ellipse",
    # 'random_curve',


    ]

ag_rules = [
'circle_center',
    'angle_bisector',
    'eq_quadrilateral',
    'eq_trapezoid',
    'eqtriangle',
    'eqdia_quadrilateral',
    'eqdistance',
    'foot',
    'incenter',
    'incenter2',
    'tangent',
    "mirror",
    "right_iso",
    "parallelogram",
    "pentagon",
    "random_square",
    "ellipse",
    'random_curve',
    "square",
    "triangle",
    "triangle12",
    "on_bline",
    "on_circle",
    "on_pline",
    "trapezoid",
    "on_line",
    'r_triangle',
    'rectangle',
    'reflect',
    'init_square',
    "trisect",
    "trisegment",
    "cc_tangent",
    "eqangle2",
    "on_aline",
    "rotate90",
    "on_tline",
    "midpointcircle",
    "excenter",
    "orthocenter",
    "r_trapezoid",
    "risos",
    "rotate_angle",
    "shift",
    "trisect",
    "on_dia",
    "eqangle3",
    "two_lines_one_circle",
    "centroid",
]

original_rules = [
    "on_circle2",
    "inter_ll",
    "one_line_one_circle",
    "colinear",
    "cc_tangent_one",
    "intersect_cl",
    "intersect_cc",
    "touches_cc",
    "touches_cc2",
    "touches_clc",
    "touches_clc2",
    "rhombus",
    "convex_quad",
    "ellipse_line_intersect",
    # "parabola",
    "incenter3",
    "circular_sector",
    "semicircle",
    "l_in_c",
    "l_out_c",
    "ll_angle",
    "ccl1",
    "ccl2",
    "ccl3",
]

